# app/config/config.yml
doctrine:
  dbal:
    driver:   pdo_mysql
    host:     '%database_host%'
    dbname:   '%database_name%'
    user:     '%database_user%'
    password: '%database_password%'
    from_email:
      address: 'mubasharhussain428@gmail.com'
      sender_name: Demo App